version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
        environment:
            - DB_CONNECTION=sqlsrv
            - DB_HOST=haarlemfestival.database.windows.net
            - DB_PORT=1433
            - DB_DATABASE=haarlemprojectdatabase
            - DB_USERNAME=HaarelmFestival
            - DB_PASSWORD=Haarlem1234

volumes:
    mysqldata: {}
